name: Chunks
version: 0.2
main: dev.keii.chunks.Chunks
api-version: '1.20'

commands:
  map:
    description: Opens the map
    usage: /map
    permission: keii.chunks.map
  chunks:
    description: Chunks plugin
    usage: /chunks [info,help,save,load]
    permission: keii.chunks.info
  chunkoverride:
    description: Set chunk override
    usage: /chunkoverride [player]?
    permission: keii.chunks.chunkoverride
  claimpower:
    description: Set claim power
    usage: /claimpower [set,add,remove] <player> <number>
    permission: keii.chunks.claimpower
permissions:
  keii.chunks.map:
    description: Permission to see the map
  keii.chunks.staffmessage:
    description: Get sent staff messages
  keii.chunks.claimpower:
    description: Modify claim power for a user
  keii.chunks.chunkoverride:
    description: Override chunk permissions
  keii.chunks.reload:
    description: Reload chunks config